### ISSUE TITLE
Suggestion: Use "Releases" feature instead of uploading binaries

### ISSUE THREAD

**Issue by timbru31** [libertyernie/vba-wii#14]
Hi,

first of all thanks for the project and the continuation :) :+1: 
However in my opinion you should not upload the .dol (binary) file in the source code.
You could instead use the Releases feature: https://github.com/libertyernie/vba-wii/releases
This allows to download older versions, too.
If you want you can even use tags on your commit etc.

Just my two cents, keep up the good work.

**Comment by libertyernie** [comment]
Good idea. If I ever make another release, I'll put it there.
