### ISSUE TITLE
Metroid 2 DX screwed up graphics (v2.3.2)

### ISSUE THREAD

**Issue by GB-CG** [libertyernie/vba-wii#15]
https://www.youtube.com/watch?v=mbQRcshFb-w

I applied a IPS colour patch file on a standard Metroid 2 game and it messed up the graphics.

**Comment by libertyernie** [comment]
I didn't do anything with the emulation core, so I don't know how to fix this. I can leave this issue open, though, since it's a known issue.

**Comment by GB-CG** [comment]
Ok.
