### ISSUE TITLE
D-Pad Up and Down issues in the VBA menu (v2.3.2)

### ISSUE THREAD

**Issue by GB-CG** [libertyernie/vba-wii#16]
I dunno if this is mentioned already, but when choosing games, the D-Pad Down input doesn't seem to work. And in the VBA settings, the Up & Down is not working either.

Gameplay-wise, it's fine.

**Comment by libertyernie** [comment]
Which controller does the D-pad not work on? Or is it all of them?

**Comment by GB-CG** [comment]
I use the official gamecube controller. (DOL-003) I may add that the control stick works in all directions but it's too sensitive.

**Comment by GB-CG** [comment]
Fixed in v2.3.5. Closing.
